---
- name: Create chroot directory tree
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /chroot
    - /chroot/named
    - /chroot/named/dev
    - /chroot/named/etc
    - /chroot/named/var
    - /chroot/named/var/named
    - /chroot/named/var/named/slaves
    - /chroot/named/var/named/data
    - /chroot/named/var/named/run

- name: Copy needed files
  copy:
    remote_src: yes
    src: "{{ item['source'] }}"
    dest: "{{ item['destination'] }}"
  with_items:
    - { source: /etc/named.conf, destination: /chroot/named/etc/named.conf }
    - { source: /etc/localtime, destination: /chroot/named/etc/localtime }

- name: Recursive copy of files
  copy:
    remote_src: yes
    src: /var/named/
    dest: /chroot/named/var/named/

- name: Change owner and group
  file:
    path: /chroot/named
    state: directory
    recurse: yes
    owner: named
    group: named

- name: Make block
  command: "{{ item }}"
  with_items:
    - "mknod /chroot/named/dev/null c 1 3"
    - "mknod /chroot/named/dev/random c 1 8"

- name: Change permissions of dev directory
  file:
    path: /chroot/named/dev
    state: directory
    mode: 0666

- name: Append line to named file
  lineinfile:
    path: /etc/sysconfig/named
    insertafter: EOF
    line: -t /chroot/named
    state: present
  notify: restart named
