---
- name: Install Bind packages
  yum:
    name:
      - bind
      - bind-utils
    state: present

- name: Start named service
  systemd:
    name: named
    state: started

- name: Open firewall port
  firewalld:
    service: dns
    permanent: yes
    state: enabled
  notify: reload firewalld

- name: Source correct variables
  include_vars: "{{ server_role }}.yml"

- name: Configure forward zone file
  template:
    src: fwd.domain.j2
    dest: /var/named/fwd.{{ domain }}.db
    mode: 0644
    owner: named
    group: named

- name: Configure main bind config file
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    mode: 0640
    owner: root
    group: named
    setype: named_conf_t
    validate: 'named-checkconf %s'
  notify: reload named

- name: Configure chroot for secondary
  include: chroot.yml
  when: server_role == "secondary"
