---
- name: Firewall Reload
  command: /usr/bin/firewall-cmd --reload
  listen: "reload firewalld"

- name: Bind Reload
  systemd:
    name: named
    state: reloaded
  listen: "reload named"

- name: Bind Restart
  systemd:
    name: named
    state: restarted
  listen: "restart named"
