---
- name: Firewall Reload
  become: yes
  command: systemctl firewall-cmd --reload
  listen: "reload firewall"

- name: Bind Reload
  become: yes
  systemd:
    name: named
    state: reloaded
  listen: "reload named"

- name: Bind Restart
  become: yes
  systemd:
    name: named
    state: restarted
  listen: "restart named"
